# Config file for all of the values to change

counts_file: results/count/counts_all.txt
# counts_raw: results/count/GSE162038_all.count.txt

treatment: Articuno_20201201_3.fastq,Articuno_20201201_4.fastq,Articuno_20201201_5.fastq,Articuno_20201201_6.fastq
# treatment: Articuno_20201201_3.fastq,Articuno_20201201_4.fastq
# treatment: LAI_vRNA1,LAI_vRNA2

control: Articuno_20201201_1.fastq,Articuno_20201201_2.fastq,Articuno_20201201_1.fastq,Articuno_20201201_2.fastq
# control: Articuno_20201201_1.fastq,Articuno_20201201_2.fastq
# control: LAI_gDNA1,LAI_gDNA2

plasmid: Articuno_20201201_7.fastq
# plasmid: TKOv3_library

sgrnas:
  # n: 8
  n: 4

heatmapCount: 50
heatmapMin: -4
heatmapMax: 4

# File to output from
output_file: nextseqArticuno_20201201_34.fastq.zscores.txt
# output_file: nextseqArticuno_20201201_4.fastq.zscores.txt
# output_file: LAI_TKOV3.zscores.txt
